/********************************************************************************
ADF - ARMA Mission Development Framework
ADF version: 2.00 / MARCH 2016

Script: Server init for connected clients
Author: Whiztler
Script version: 1.20

File: initPlayerServer.sqf
********************************************************************************
DO NOT edit this file. To set-up and configure your mission, edit the files in
the  'mission\1-config\'  folder.
************************************************************************************************/

 // Reporting. Do NOT edit/remove
if (isMultiplayer) then {
	diag_log format ["ADF RPT: Init - executing initPlayerServer.sqf -- player: %1 -- JIP: %2", _this select 0, _this select 1];
} else {
	diag_log "ADF RPT: Init - executing initPlayerServer.sqf";
};

// Init


// Cuyrator inits
{_x addCuratorEditableObjects [[_this select 0], true]} forEach allCurators;  

